version: "3.7"
services:
  apiwrapper:
    image: "simpleopenaiapiwrapper:latest"
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
       - _OPENAI_API_KEY=${_OPENAI_API_KEY}
       - _OPENAI_API_BASE=${_OPENAI_API_BASE}
 

    volumes:
      - "volume1:/usr/share/fastapi/data"

volumes:
  volume1:
