services:
  apiwrapper:
    image: "simpleopenaiapiwrapper:latest"
    ports:
      - "8888:8888"
      - "80:80"
    env_file:
      - .env
    environment:
       - _OPENAI_API_KEY=${_OPENAI_API_KEY}
       - _OPENAI_API_BASE=${_OPENAI_API_BASE}
       - _OPENAI_API_VERSION=${_OPENAI_API_VERSION}
 

    volumes:
      - "volume1:/usr/share/fastapi/data"

volumes:
  volume1:
